# Используем Maven с Java 11
image: maven:3.8-openjdk-11

default:
  tags:
    - testrunner

stages:
  - test

integration_test_with_allure:
  stage: test
  script:
    - mvn clean test
    - mvn allure:report
    - mkdir -p allureReports
    - cp -r target/site/allure-maven-plugin/* allureReports/
  artifacts:
    when: always
    paths:
      - allureReports/
    expire_in: 1 week
